#!/bin/bash
# Sync a paired jupyter notebook and standalone py file. Prior
# to running, create a paired notebook and py file with:
# jupytext --set-formats ipynb,py notebook.ipynb
# 
# Open an interactive session after syncing by:
# passing the -o flag
#
# Execute all notebook cells and open an interactive session by:
# passing the -e flag

while getopts ":oe" opt; do
  case $opt in
    o)
      jupytext --sync $2
      ;;
    e)
      jupytext --sync $2
      papermill $2 $2 
      ;;      
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done

if [ $OPTIND -eq 1 ]; then 
	jupytext --sync $1
fi

