#!/bin/bash
IFS=$'\n'       # make newlines the only separator

FILENAME=$1
LINES=$(cat $FILENAME)

for LINE in $LINES
do
    str="$LINE"
    target=$(echo "$str" | cut -c4-)    
    echo "target: $target"

    # dirname = $(dirname $str)
    # echo "$dirname"

    # zippath

done

unset IFS